name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.email "varadpensalwar@gmail.com"
          git config --global user.name "Varad Pensalwar"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/varadpensalwar/github-finder.git
          git push gitlab main --force
